[package]
name = "directhci-ble"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
readme = "README.md"

[dependencies]
bt-hci.workspace = true
critical-section = { version = "1", features = ["std"] }
directhci-bt-hci.workspace = true
directhci-client.workspace = true
embassy-time = { version = "0.5.0", features = ["std", "generic-queue-8"] }
tokio = { workspace = true, features = ["rt", "sync", "time", "macros"] }
trouble-host = { workspace = true, default-features = false, features = [
    "central",
    "gatt",
    "scan",
    "default-packet-pool",
    "default-packet-pool-mtu-251",
] }
