[package]
name = "directhci-bt-hci"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bt-hci.workspace = true
directhci-client.workspace = true
directhci-core.workspace = true
embedded-io.workspace = true
tokio = { workspace = true, features = ["sync"] }
